### ISSUE TITLE
Add global and per-context flag defaults

### ISSUE THREAD

**Issue by MarcosCela** [MarcosCela/dr#5]
**Is your feature request related to a problem? Please describe.**
Right now the only way to setup modifiers is to use flags for every command, and this can get tiresome really really quick.

**Describe the solution you'd like**
User should be able to setup defaults like:
```yaml
currentContext: default
output: json
contexts:
- name: default
  url: http://localhost:5000
  user: ""
  trusted: true
  output: plain
  showTags: true
```

These values should be enabled/disabled globally, and per-context.
The priorities should be lilke this:

- First check global and apply them.
- Then check per-context and apply them, override any global.
- At last, check flag values and apply them, override any others.
